### ISSUE TITLE
Plugin not working on github pages

### ISSUE THREAD

**Issue by vvasuki** [joshdavenport/jekyll-regex-replace#2]
Any idea why?

Details at https://stackoverflow.com/questions/53270363/jekyll-ruby-plugin-not-working-on-github-pages-but-working-locally

**Comment by joshdavenport** [comment]
This is a limitation of GitHub pages itself, only certain plugins can be used there. They're listed here: https://help.github.com/articles/configuring-jekyll-plugins/

Your only option here would be to generate locally and push the result of the jekyll build.
